### ISSUE TITLE
Dodati primer sa MUSICO-m

### ISSUE THREAD

**Issue by imilos** [Andreja28/cloud-workflows#1]
Dokumentovati primer u `Readme.md`. Da se ne vidi hostname na koji se kacimo. Primer treba da ima 2 noda; jedan nod da zipuje fajlove, a drugi da radi poziv servisa.

**Comment by Andreja28** [comment]
Komitovao sam primer sa jednim nodom. Problem kod zipovanja fajlova predstavlja to sto u toilu ne mogu da odrzim strukturu direktorijuma koja mi je potrebna u zipu. Imam neke ideje kako bih ovo mogao da resim, ali sam za sada komitovao primer sa samo jednim nodom, jer ne znam koliko ce mi vremena biti potrebno za resavanje ovog problema.
